### ISSUE TITLE
Don't save

### ISSUE THREAD

**Issue by DiscordPug** [AnIdiotsGuide/guidebot-class#33]
Settings Don't saving 
i reload my bot all settings make default

**Comment by eslachance** [comment]
Guidebot is known to be functional and settings do save correctly. If you're having issues, it might be a host problem. Some hosts such as Heroku do not allow files to be saved, and this is not a code issue, it's just something that would require an external database and more complexity for most other users. 

If you have further questions, please join the [Idiot's Guide Discord Server](https://discord.gg/4NE4bk7).
