### ISSUE TITLE
eval can't clean

### ISSUE THREAD

**Issue by nesmon** [AnIdiotsGuide/guidebot-class#34]
Eval can't clean because he need clean function but any clean function exist in all project.
I try to use the basic function.js use for guidebot (not class version) but not work becaus is not with class methode :/
How can solve this ?

**Comment by cfanoulis** [comment]
I'm claiming this issue, and I'm implementing a fix as we speak

**Comment by eslachance** [comment]
Resolved by https://github.com/AnIdiotsGuide/guidebot-class/commit/bc11f2ebd289f7962dfe17757f156f23e1b9f7fe

Please pull again to update your code.
