### ISSUE TITLE
Possible awaitReply error.

### ISSUE THREAD

**Issue by Odaiba-Arthur** [AnIdiotsGuide/guidebot-class#38]
Currently, await reply's filter is: m.author.id = msg.author.id
shouldn't this be: m.author.id === msg.author.id

Using the provided code was causing ID issues:
![image](https://user-images.githubusercontent.com/34529735/72674275-763c0c00-3ac0-11ea-9c00-0c31055c964c.png)

Cheers!

**Comment by AndrewJWin** [comment]
You are correct:

https://github.com/AnIdiotsGuide/guidebot-class/blob/master/index.js#L173
> ``const filter = m=>m.author.id = msg.author.id;``
Should be:
> ``const filter = m=>m.author.id === msg.author.id;``

Feel free to attach a PR Request with a fix!

**Comment by YorkAARGH** [comment]
This was fixed in a prior version, but what I think happened was a small design oversight and some code got jumbled.

Fixed here https://github.com/AnIdiotsGuide/guidebot-class/commit/a971a64ec2306b70f541e371812f2846aae8f2e1
