### ISSUE TITLE
Ping command has a issue!

### ISSUE THREAD

**Issue by raj123567** [AnIdiotsGuide/guidebot-class#40]
` 💙: ${Math.round(this.client.ping)}ms.`
should be
`💙: ${Math.round(this.client.ping)}ms.`
![image](https://user-images.githubusercontent.com/65060180/84789068-76a7e700-b00d-11ea-836a-f8d815c91eeb.png)

**Comment by c0dine** [comment]
I'm pretty sure you just wrote the same thing twice

**Comment by 1lix** [comment]
frking lol even ever you try to show thats your smart xd lol

**Comment by YorkAARGH** [comment]
fixed via #41
