### ISSUE TITLE
When I try to set Bot Owner it keeps saying I am bot admin

### ISSUE THREAD

**Issue by SweetieRick** [AnIdiotsGuide/guidebot-class#51]
I recently tried to use this boilerplate code for my own bot, which application is transferred to a team.
Whenever I try to set the Bot Ownership, the bot keeps saying I am not the owner.
There is a way other than remaking the entire application from zero?

*Help is really helpful 👍 *

**Comment by thetayloredman** [comment]
Are you sure the config has a STRING not an ARRAY for it's owner?

**Comment by YorkAARGH** [comment]
This is very strange as I am very certain that I added team functionality to the boiler plate.

**Comment by eslachance** [comment]
Unfortunately not the case, we can see it's looking directly at the bot's owner ID. Let's have a look-see at that code...
`check: (message) => message.client.appInfo.owner.id === message.author.id`

**Comment by eslachance** [comment]
Should now be resolved for guidebot-class! see /events/ready.js and the updated config-example.js
