### ISSUE TITLE
awaitReaction not reacting

### ISSUE THREAD

**Issue by thomasstr** [AnIdiotsGuide/guidebot-class#52]
I am struggling trying to understand why the awaitReaction function works on the simple one-file bot index.js and not with my guidebot. Both files in the gist below.

Can someone maybe help me in the correct direction?

https://gist.github.com/thomasstr/625bd408617e0f8cf1a28f291e7a86fc

**Comment by YorkAARGH** [comment]
Honestly, I'm not sure why it's not working for you, the code looks identical
